name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      SOLUTION_PATH: ..\..\src\TSP.sln

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run:
          dotnet restore ${{env.SOLUTION_PATH}}
    - name: Build
      run: dotnet build ${{env.SOLUTION_PATH}} --no-restore
    - name: Test
      run: dotnet test ${{env.SOLUTION_PATH}} --no-build --verbosity normal